### signup
POST http://localhost:8080/user/signup
Content-Type: application/json

{
    "userId": "user",
    "password": "8888",
    "name": "사용자",
    "phone": "010-8888-8888",
    "memberType": "ROLE_USER"
}

### signin
POST http://localhost:8080/user/signin
Content-Type: application/json

{
    "userId": "melon",
    "password": "4444"
}

### delete member
DELETE http://localhost:8080/user/14
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwibWVtYmVyVHlwZSI6IlJPTEVfVVNFUiIsImlhdCI6MTY5OTE2Mjg5NywiZXhwIjoxNjk5MTY2NDk3fQ.WqKi2hnYnspDQs4M5HL2JwLzrb347tHfit8thj2btTFUDq6K4eI6xHJugn4-ruETj51ivufa7P0oLykUPgRbUA